spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
      minimum-idle: 2
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: TRACE